In [1]:

import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(
    "../Dataset/DataCoSupplyChainDataset.csv",
    encoding="latin1"
)

print(df.shape)

(180519, 53)

In [3]:
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

In [4]:
df.columns.tolist()

['Type',
 'Days for shipping (real)',
 'Days for shipment (scheduled)',
 'Benefit per order',
 'Sales per customer',
 'Delivery Status',
 'Late_delivery_risk',
 'Category Id',
 'Category Name',
 'Customer City',
 'Customer Country',
 'Customer Email',
 'Customer Fname',
 'Customer Id',
 'Customer Lname',
 'Customer Password',
 'Customer Segment',
 'Customer State',
 'Customer Street',
 'Customer Zipcode',
 'Department Id',
 'Department Name',
 'Latitude',
 'Longitude',
 'Market',
 'Order City',
 'Order Country',
 'Order Customer Id',
 'order date (DateOrders)',
 'Order Id',
 'Order Item Cardprod Id',
 'Order Item Discount',
 'Order Item Discount Rate',
 'Order Item Id',
 'Order Item Product Price',
 'Order Item Profit Ratio',
 'Order Item Quantity',
 'Sales',
 'Order Item Total',
 'Order Profit Per Order',
 'Order Region',
 'Order State',
 'Order Status',
 'Order Zipcode',
 'Product Card Id',
 'Product Category Id',
 'Product Description',
 'Product Image',
 'Product Name',
 'Product Price',
 'Product Status',
 'shipping date (DateOrders)',
 'Shipping Mode']

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  str
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  str
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  str
 9   Customer City                  180519 non-null  str
 10  Customer Country               180519 non-null  str
 11  Customer Email                 180519 non-null  str
 12  Customer Fname                 180519 non-null  str
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  str
 15  Customer Password              180519 non-null  str
 16  Customer Segment               180519 non-null  str
 17  Customer State                 180519 non-null  str
 18  Customer Street                180519 non-null  str
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  str
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  str
 25  Order City                     180519 non-null  str
 26  Order Country                  180519 non-null  str
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  str
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  str
 41  Order State                    180519 non-null  str
 42  Order Status                   180519 non-null  str
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  str
 48  Product Name                   180519 non-null  str
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  str
 52  Shipping Mode                  180519 non-null  str
dtypes: float64(15), int64(14), str(24)
memory usage: 73.0 MB

In [6]:
df.isnull().sum().sort_values(ascending=False)

Product Description              180519
Order Zipcode                    155679
Customer Lname                        8
Customer Zipcode                      3
Days for shipment (scheduled)         0
Sales per customer                    0
Benefit per order                     0
Delivery Status                       0
Late_delivery_risk                    0
Customer City                         0
Customer Country                      0
Category Id                           0
Category Name                         0
Customer Fname                        0
Customer Email                        0
Customer Password                     0
Customer Id                           0
Customer Segment                      0
Customer State                        0
Days for shipping (real)              0
Type                                  0
Department Id                         0
Customer Street                       0
Department Name                       0
Latitude                              0
Order City                            0
Order Country                         0
Longitude                             0
Market                                0
Order Id                              0
Order Item Cardprod Id                0
Order Item Discount                   0
Order Item Discount Rate              0
Order Item Id                         0
Order Item Product Price              0
Order Customer Id                     0
order date (DateOrders)               0
Order Item Quantity                   0
Order Item Profit Ratio               0
Order Profit Per Order                0
Sales                                 0
Order Region                          0
Order State                           0
Order Status                          0
Order Item Total                      0
Product Card Id                       0
Product Category Id                   0
Product Image                         0
Product Name                          0
Product Price                         0
Product Status                        0
shipping date (DateOrders)            0
Shipping Mode                         0
dtype: int64

In [7]:
print("Shape:")
print(df.shape)

print("\nFirst 5 rows:")
display(df.head())

print("\nColumns:")
print(df.columns.tolist())

print("\nData Info:")
df.info()

print("\nMissing Values:")
display(df.isnull().sum().sort_values(ascending=False))

print("\nDuplicate Rows:")
print(df.duplicated().sum())

Shape:
(180519, 53)

First 5 rows:

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

Columns:
['Type', 'Days for shipping (real)', 'Days for shipment (scheduled)', 'Benefit per order', 'Sales per customer', 'Delivery Status', 'Late_delivery_risk', 'Category Id', 'Category Name', 'Customer City', 'Customer Country', 'Customer Email', 'Customer Fname', 'Customer Id', 'Customer Lname', 'Customer Password', 'Customer Segment', 'Customer State', 'Customer Street', 'Customer Zipcode', 'Department Id', 'Department Name', 'Latitude', 'Longitude', 'Market', 'Order City', 'Order Country', 'Order Customer Id', 'order date (DateOrders)', 'Order Id', 'Order Item Cardprod Id', 'Order Item Discount', 'Order Item Discount Rate', 'Order Item Id', 'Order Item Product Price', 'Order Item Profit Ratio', 'Order Item Quantity', 'Sales', 'Order Item Total', 'Order Profit Per Order', 'Order Region', 'Order State', 'Order Status', 'Order Zipcode', 'Product Card Id', 'Product Category Id', 'Product Description', 'Product Image', 'Product Name', 'Product Price', 'Product Status', 'shipping date (DateOrders)', 'Shipping Mode']

Data Info:
<class 'pandas.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  str
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  str
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  str
 9   Customer City                  180519 non-null  str
 10  Customer Country               180519 non-null  str
 11  Customer Email                 180519 non-null  str
 12  Customer Fname                 180519 non-null  str
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  str
 15  Customer Password              180519 non-null  str
 16  Customer Segment               180519 non-null  str
 17  Customer State                 180519 non-null  str
 18  Customer Street                180519 non-null  str
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  str
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  str
 25  Order City                     180519 non-null  str
 26  Order Country                  180519 non-null  str
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  str
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  str
 41  Order State                    180519 non-null  str
 42  Order Status                   180519 non-null  str
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  str
 48  Product Name                   180519 non-null  str
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  str
 52  Shipping Mode                  180519 non-null  str
dtypes: float64(15), int64(14), str(24)
memory usage: 73.0 MB

Missing Values:

Product Description              180519
Order Zipcode                    155679
Customer Lname                        8
Customer Zipcode                      3
Days for shipment (scheduled)         0
Sales per customer                    0
Benefit per order                     0
Delivery Status                       0
Late_delivery_risk                    0
Customer City                         0
Customer Country                      0
Category Id                           0
Category Name                         0
Customer Fname                        0
Customer Email                        0
Customer Password                     0
Customer Id                           0
Customer Segment                      0
Customer State                        0
Days for shipping (real)              0
Type                                  0
Department Id                         0
Customer Street                       0
Department Name                       0
Latitude                              0
Order City                            0
Order Country                         0
Longitude                             0
Market                                0
Order Id                              0
Order Item Cardprod Id                0
Order Item Discount                   0
Order Item Discount Rate              0
Order Item Id                         0
Order Item Product Price              0
Order Customer Id                     0
order date (DateOrders)               0
Order Item Quantity                   0
Order Item Profit Ratio               0
Order Profit Per Order                0
Sales                                 0
Order Region                          0
Order State                           0
Order Status                          0
Order Item Total                      0
Product Card Id                       0
Product Category Id                   0
Product Image                         0
Product Name                          0
Product Price                         0
Product Status                        0
shipping date (DateOrders)            0
Shipping Mode                         0
dtype: int64

Duplicate Rows:
0

In [8]:
drop_cols = [
    "Customer Email",
    "Customer Password",
    "Customer Fname",
    "Customer Lname",
    "Customer Street",
    "Product Image",
    "Product Description",
    "Order Zipcode"
]

df = df.drop(columns=drop_cols)

In [9]:
df.shape

(180519, 45)

In [10]:
df.columns = (
    df.columns
    .str.lower()
    .str.strip()
    .str.replace(" ", "_")
    .str.replace("(", "", regex=False)
    .str.replace(")", "", regex=False)
)

In [11]:
df.columns.tolist()

['type',
 'days_for_shipping_real',
 'days_for_shipment_scheduled',
 'benefit_per_order',
 'sales_per_customer',
 'delivery_status',
 'late_delivery_risk',
 'category_id',
 'category_name',
 'customer_city',
 'customer_country',
 'customer_id',
 'customer_segment',
 'customer_state',
 'customer_zipcode',
 'department_id',
 'department_name',
 'latitude',
 'longitude',
 'market',
 'order_city',
 'order_country',
 'order_customer_id',
 'order_date_dateorders',
 'order_id',
 'order_item_cardprod_id',
 'order_item_discount',
 'order_item_discount_rate',
 'order_item_id',
 'order_item_product_price',
 'order_item_profit_ratio',
 'order_item_quantity',
 'sales',
 'order_item_total',
 'order_profit_per_order',
 'order_region',
 'order_state',
 'order_status',
 'product_card_id',
 'product_category_id',
 'product_name',
 'product_price',
 'product_status',
 'shipping_date_dateorders',
 'shipping_mode']

In [12]:
df["order_date_dateorders"] = pd.to_datetime(
    df["order_date_dateorders"])

df["shipping_date_dateorders"] = pd.to_datetime(
    df["shipping_date_dateorders"]
)

In [13]:
df[[
    "order_date_dateorders",
    "shipping_date_dateorders"
]].dtypes

order_date_dateorders       datetime64[us]
shipping_date_dateorders    datetime64[us]
dtype: object

In [14]:
df[[
    "order_date_dateorders",
    "shipping_date_dateorders"
]].isnull().sum()

order_date_dateorders       0
shipping_date_dateorders    0
dtype: int64

In [15]:
numeric_cols = [
    "days_for_shipping_real",
    "days_for_shipment_scheduled",
    "benefit_per_order",
    "sales_per_customer",
    "late_delivery_risk",
    "order_item_discount",
    "order_item_discount_rate",
    "order_item_product_price",
    "order_item_profit_ratio",
    "order_item_quantity",
    "sales",
    "order_item_total",
    "order_profit_per_order",
    "product_price"
]

df[numeric_cols].describe().T

,count,mean,std,min,25%,50%,75%,max
days_for_shipping_real,180519.0,3.497654,1.623722,0.00000,2.000000,3.000000,5.000000,6.000000
days_for_shipment_scheduled,180519.0,2.931847,1.374449,0.00000,2.000000,4.000000,4.000000,4.000000
benefit_per_order,180519.0,21.974989,104.433526,-4274.97998,7.000000,31.520000,64.800003,911.799988
sales_per_customer,180519.0,183.107609,120.043670,7.49000,104.379997,163.990005,247.399994,1939.989990
late_delivery_risk,180519.0,0.548291,0.497664,0.00000,0.000000,1.000000,1.000000,1.000000
order_item_discount,180519.0,20.664741,21.800901,0.00000,5.400000,14.000000,29.990000,500.000000
order_item_discount_rate,180519.0,0.101668,0.070415,0.00000,0.040000,0.100000,0.160000,0.250000
order_item_product_price,180519.0,141.232550,139.732492,9.99000,50.000000,59.990002,199.990005,1999.989990
order_item_profit_ratio,180519.0,0.120647,0.466796,-2.75000,0.080000,0.270000,0.360000,0.500000
order_item_quantity,180519.0,2.127638,1.453451,1.00000,1.000000,1.000000,3.000000,5.000000
sales,180519.0,203.772096,132.273077,9.99000,119.980003,199.919998,299.950012,1999.989990
order_item_total,180519.0,183.107609,120.043670,7.49000,104.379997,163.990005,247.399994,1939.989990
order_profit_per_order,180519.0,21.974989,104.433526,-4274.97998,7.000000,31.520000,64.800003,911.799988
product_price,180519.0,141.232550,139.732492,9.99000,50.000000,59.990002,199.990005,1999.989990

In [16]:
df["late_delivery_risk"].value_counts()

late_delivery_risk
1    98977
0    81542
Name: count, dtype: int64

In [17]:
df["days_for_shipping_real"].value_counts().sort_index()

days_for_shipping_real
0     5080
1     4657
2    56618
3    28765
4    28513
5    28163
6    28723
Name: count, dtype: int64

In [18]:
df["days_for_shipment_scheduled"].value_counts().sort_index()

days_for_shipment_scheduled
0      9737
1     27814
2     35216
4    107752
Name: count, dtype: int64

In [19]:
df["order_item_discount"].describe(percentiles=[.90, .95, .99])

count    180519.000000
mean         20.664741
std          21.800901
min           0.000000
90%          49.980000
95%          62.500000
99%          95.860001
max         500.000000
Name: order_item_discount, dtype: float64

In [20]:
df[df["order_item_discount"] == 500][[
    "sales",
    "order_item_discount",
    "order_item_discount_rate",
    "order_item_total",
    "order_item_product_price"
]].head(10)

,sales,order_item_discount,order_item_discount_rate,order_item_total,order_item_product_price
12606,1999.98999,500.0,0.25,1499.98999,1999.98999

In [21]:
categorical_cols = [
    "type",
    "delivery_status",
    "category_name",
    "customer_segment",
    "department_name",
    "market",
    "order_region",
    "order_status",
    "shipping_mode"
]

for col in categorical_cols:
    print(f"\n--- {col} ---")
    print(df[col].value_counts())

--- type ---
type
DEBIT       69295
TRANSFER    49883
PAYMENT     41725
CASH        19616
Name: count, dtype: int64

--- delivery_status ---
delivery_status
Late delivery        98977
Advance shipping     41592
Shipping on time     32196
Shipping canceled     7754
Name: count, dtype: int64

--- category_name ---
category_name
Cleats                  24551
Men's Footwear          22246
Women's Apparel         21035
Indoor/Outdoor Games    19298
Fishing                 17325
Water Sports            15540
Camping & Hiking        13729
Cardio Equipment        12487
Shop By Sport           10984
Electronics              3156
Accessories              1780
Golf Balls               1475
Girls' Apparel           1201
Golf Gloves              1070
Trade-In                  974
Video Games               838
Children's Clothing       652
Women's Clothing          650
Baseball & Softball       632
Hockey                    614
Cameras                   592
Toys                      529
Golf Shoes                524
Pet Supplies              492
Crafts                    484
Garden                    484
DVDs                      483
Computers                 442
Golf Apparel              441
Hunting & Shooting        440
Music                     434
Consumer Electronics      431
Boxing & MMA              423
Books                     405
Kids' Golf Clubs          384
Health and Beauty         362
Sporting Goods            357
Lacrosse                  343
Tennis & Racquet          328
Fitness Accessories       309
Men's Golf Clubs          283
CDs                       271
Men's Clothing            208
Baby                      207
Women's Golf Clubs        181
Soccer                    138
Strength Training         111
As Seen on  TV!            68
Basketball                 67
Golf Bags & Carts          61
Name: count, dtype: int64

--- customer_segment ---
customer_segment
Consumer       93504
Corporate      54789
Home Office    32226
Name: count, dtype: int64

--- department_name ---
department_name
Fan Shop              66861
Apparel               48998
Golf                  33220
Footwear              14525
Outdoors               9686
Fitness                2479
Discs Shop             2026
Technology             1465
Pet Shop                492
Book Shop               405
Health and Beauty       362
Name: count, dtype: int64

--- market ---
market
LATAM           51594
Europe          50252
Pacific Asia    41260
USCA            25799
Africa          11614
Name: count, dtype: int64

--- order_region ---
order_region
Central America    28341
Western Europe     27109
South America      14935
Oceania            10148
Northern Europe     9792
Southeast Asia      9539
Southern Europe     9431
Caribbean           8318
West of USA         7993
South Asia          7731
Eastern Asia        7280
East of USA         6915
West Asia           6009
US Center           5887
South of  USA       4045
Eastern Europe      3920
West Africa         3696
North Africa        3232
East Africa         1852
Central Africa      1677
Southern Africa     1157
Canada               959
Central Asia         553
Name: count, dtype: int64

--- order_status ---
order_status
COMPLETE           59491
PENDING_PAYMENT    39832
PROCESSING         21902
PENDING            20227
CLOSED             19616
ON_HOLD             9804
SUSPECTED_FRAUD     4062
CANCELED            3692
PAYMENT_REVIEW      1893
Name: count, dtype: int64

--- shipping_mode ---
shipping_mode
Standard Class    107752
Second Class       35216
First Class        27814
Same Day            9737
Name: count, dtype: int64

In [22]:
for col in categorical_cols:
    spaces = df[col].astype(str).str.strip().ne(df[col].astype(str)).sum()
    print(col, spaces)

type 0
delivery_status 0
category_name 1475
customer_segment 0
department_name 362
market 0
order_region 17925
order_status 0
shipping_mode 0

In [23]:
for col in categorical_cols:
    df[col] = (
        df[col]
        .astype(str)
        .str.strip()
        .str.replace(r"\s+", " ", regex=True)
    )

In [24]:
for col in categorical_cols:
    spaces = (
        df[col]
        .astype(str)
        .str.strip()
        .ne(df[col].astype(str))
    ).sum()
    
    print(col, spaces)

type 0
delivery_status 0
category_name 0
customer_segment 0
department_name 0
market 0
order_region 0
order_status 0
shipping_mode 0

In [25]:
df["order_region"].value_counts()

order_region
Central America    28341
Western Europe     27109
South America      14935
Oceania            10148
Northern Europe     9792
Southeast Asia      9539
Southern Europe     9431
Caribbean           8318
West of USA         7993
South Asia          7731
Eastern Asia        7280
East of USA         6915
West Asia           6009
US Center           5887
South of USA        4045
Eastern Europe      3920
West Africa         3696
North Africa        3232
East Africa         1852
Central Africa      1677
Southern Africa     1157
Canada               959
Central Asia         553
Name: count, dtype: int64

In [26]:
df[df["customer_zipcode"].isnull()][[
    "customer_id",
    "customer_city",
    "customer_state",
    "customer_country",
    "customer_zipcode"
]]

,customer_id,customer_city,customer_state,customer_country,customer_zipcode
35704,14577,CA,95758,EE. UU.,NaN
46440,17171,CA,95758,EE. UU.,NaN
82511,14046,CA,91732,EE. UU.,NaN

In [27]:
df.isnull().sum().sort_values(ascending=False).head(10)

customer_zipcode               3
days_for_shipping_real         0
days_for_shipment_scheduled    0
benefit_per_order              0
type                           0
delivery_status                0
late_delivery_risk             0
category_id                    0
category_name                  0
customer_city                  0
dtype: int64

In [28]:
df["shipping_delay"] = (
    df["days_for_shipping_real"]
    - df["days_for_shipment_scheduled"]
)

df[[
    "days_for_shipping_real",
    "days_for_shipment_scheduled",
    "shipping_delay"
]].head(10)

   days_for_shipping_real  days_for_shipment_scheduled  shipping_delay
0                       3                            4              -1
1                       5                            4               1
2                       4                            4               0
3                       3                            4              -1
4                       2                            4              -2
5                       6                            4               2
6                       2                            1               1
7                       2                            1               1
8                       3                            2               1
9                       2                            1               1

In [29]:
df["order_year"] = df["order_date_dateorders"].dt.year

df["order_month"] = df["order_date_dateorders"].dt.month

df["order_month_name"] = df["order_date_dateorders"].dt.month_name().str[:3]

df["order_quarter"] = df["order_date_dateorders"].dt.quarter

df["order_month_year"] = (
    df["order_date_dateorders"]
    .dt.to_period("M")
    .astype(str)
)

In [30]:
df[[
    "order_date_dateorders",
    "order_year",
    "order_month",
    "order_month_name",
    "order_quarter",
    "order_month_year"
]].head(10)

,order_date_dateorders,order_year,order_month,order_month_name,order_quarter,order_month_year
0,2018-01-31 22:56:00,2018,1,Jan,1,2018-01
1,2018-01-13 12:27:00,2018,1,Jan,1,2018-01
2,2018-01-13 12:06:00,2018,1,Jan,1,2018-01
3,2018-01-13 11:45:00,2018,1,Jan,1,2018-01
4,2018-01-13 11:24:00,2018,1,Jan,1,2018-01
5,2018-01-13 11:03:00,2018,1,Jan,1,2018-01
6,2018-01-13 10:42:00,2018,1,Jan,1,2018-01
7,2018-01-13 10:21:00,2018,1,Jan,1,2018-01
8,2018-01-13 10:00:00,2018,1,Jan,1,2018-01
9,2018-01-13 09:39:00,2018,1,Jan,1,2018-01

In [31]:
df["profit_margin"] = np.where(
    df["sales"] != 0,
    (df["order_profit_per_order"] / df["sales"]) * 100,
    0
)

In [32]:
df[[
    "sales",
    "order_profit_per_order",
    "profit_margin"
]].head(10)

    sales  order_profit_per_order  profit_margin
0  327.75               91.250000      27.841342
1  327.75             -249.089996     -75.999999
2  327.75             -247.779999     -75.600305
3  327.75               22.860001       6.974829
4  327.75              134.210007      40.948896
5  327.75               18.580000       5.668955
6  327.75               95.180000      29.040427
7  327.75               68.430000      20.878719
8  327.75              133.720001      40.799390
9  327.75              132.149994      40.320364

In [33]:
df["profit_margin"].describe()

count    180519.000000
mean         10.832612
std          42.059372
min        -274.999998
25%           6.224000
50%          24.251212
75%          33.601431
max          50.044288
Name: profit_margin, dtype: float64

In [34]:
df["delivery_flag"] = np.where(
    df["late_delivery_risk"] == 1,
    "Late",
    "On Time"
)

In [35]:
df["delivery_flag"].value_counts()

delivery_flag
Late       98977
On Time    81542
Name: count, dtype: int64

In [36]:
print("Shape:", df.shape)

print("\nMissing values:")
print(df.isnull().sum().sort_values(ascending=False).head(10))

print("\nDuplicate rows:")
print(df.duplicated().sum())

print("\nNew features:")
print([
    "shipping_delay",
    "order_year",
    "order_month",
    "order_month_name",
    "order_quarter",
    "profit_margin",
    "order_month_year",
    "delivery_flag"
])

Shape: (180519, 53)

Missing values:
customer_zipcode               3
days_for_shipping_real         0
days_for_shipment_scheduled    0
benefit_per_order              0
type                           0
sales_per_customer             0
delivery_status                0
category_id                    0
late_delivery_risk             0
customer_city                  0
dtype: int64

Duplicate rows:
0

New features:
['shipping_delay', 'order_year', 'order_month', 'order_month_name', 'order_quarter', 'profit_margin', 'order_month_year', 'delivery_flag']

In [37]:
# import pandas as pd
# import numpy as np
# from pathlib import Path

# output_file = Path("./supply_chain.sql")

# # PostgreSQL data type mapping
# def postgres_type(dtype):
#     if pd.api.types.is_integer_dtype(dtype):
#         return "BIGINT"
#     elif pd.api.types.is_float_dtype(dtype):
#         return "DOUBLE PRECISION"
#     elif pd.api.types.is_datetime64_any_dtype(dtype):
#         return "TIMESTAMP"
#     else:
#         return "TEXT"

# # Create SQL file
# with open(output_file, "w", encoding="utf-8") as f:

#     # 1. Drop table if it already exists
#     f.write("DROP TABLE IF EXISTS supply_chain;\n\n")

#     # 2. Create table
#     f.write("CREATE TABLE supply_chain (\n")

#     columns = []
#     for col in df.columns:
#         columns.append(
#             f'    "{col}" {postgres_type(df[col].dtype)}'
#         )

#     f.write(",\n".join(columns))
#     f.write("\n);\n\n")

#     # 3. COPY command
#     column_names = ", ".join(f'"{col}"' for col in df.columns)

#     f.write(
#         f"COPY supply_chain ({column_names}) FROM STDIN WITH (FORMAT csv, HEADER true, NULL '\\N');\n"
#     )

#     # 4. Write CSV data
#     temp_csv = Path("./supply_chain_temp.csv")

#     df.to_csv(
#         temp_csv,
#         index=False,
#         encoding="utf-8",
#         na_rep="\\N"
#     )

#     # Add CSV contents to SQL file
#     with open(temp_csv, "r", encoding="utf-8") as csv_file:
#         f.write(csv_file.read())

#     f.write("\\.\n")

# print("SQL file created successfully!")
# print(output_file.resolve())
# print(f"File size: {output_file.stat().st_size / (1024**2):.2f} MB")

## kpi analysis

In [38]:
total_orders = df["order_id"].nunique()

print("Total Orders:", total_orders)

Total Orders: 65752

In [39]:
total_revenue = df["sales"].sum()

print("Total Revenue:", total_revenue)

Total Revenue: 36784735.01337984

In [40]:
total_profit = df["order_profit_per_order"].sum()

print(f"Total Profit: ${total_profit:,.2f}")

Total Profit: $3,966,902.97

In [41]:
total_units = df["order_item_quantity"].sum()

print(f"Total Units Sold: {total_units:,}")

Total Units Sold: 384,079

In [42]:
aov = total_revenue / total_orders

print(f"Average Order Value: ${aov:,.2f}")

Average Order Value: $559.45

In [43]:
overall_profit_margin = (total_profit / total_revenue) * 100

print(f"Overall Profit Margin: {overall_profit_margin:.2f}%")

Overall Profit Margin: 10.78%

In [44]:
late_delivery_rate = df["late_delivery_risk"].mean() * 100

print(f"Late Delivery Rate: {late_delivery_rate:.2f}%")

Late Delivery Rate: 54.83%

In [45]:
avg_shipping_time = df["days_for_shipping_real"].mean()

print(f"Average Shipping Time: {avg_shipping_time:.2f} days")

Average Shipping Time: 3.50 days

In [46]:
avg_scheduled_time = df["days_for_shipment_scheduled"].mean()

print(f"Average Scheduled Shipping Time: {avg_scheduled_time:.2f} days")

Average Scheduled Shipping Time: 2.93 days

In [47]:
avg_shipping_delay = df["shipping_delay"].mean()

print(f"Average Shipping Delay: {avg_shipping_delay:.2f} days")

Average Shipping Delay: 0.57 days

In [63]:
df["discount_band"] = pd.cut(
    df["order_item_discount_rate"] * 100,
    bins=[-0.01, 0, 5, 10, 20, 25],
    labels=[
        "No Discount",
        "Low (1-5%)",
        "Medium (6-10%)",
        "High (11-20%)",
        "Very High (21-25%)"
    ]
)

In [64]:
df["discount_band"].value_counts().sort_index()

discount_band
No Discount           10028
Low (1-5%)            40114
Medium (6-10%)        40116
High (11-20%)         70203
Very High (21-25%)    20058
Name: count, dtype: int64

In [67]:
import os

print(os.path.abspath("./supply_chain_cleaned.csv"))

C:\Users\thris\OneDrive\Desktop\Supplychain Anlysis\python\supply_chain_cleaned.csv

In [68]:
print(df.shape)

print(df.columns.tolist())

(180519, 54)
['type', 'days_for_shipping_real', 'days_for_shipment_scheduled', 'benefit_per_order', 'sales_per_customer', 'delivery_status', 'late_delivery_risk', 'category_id', 'category_name', 'customer_city', 'customer_country', 'customer_id', 'customer_segment', 'customer_state', 'customer_zipcode', 'department_id', 'department_name', 'latitude', 'longitude', 'market', 'order_city', 'order_country', 'order_customer_id', 'order_date_dateorders', 'order_id', 'order_item_cardprod_id', 'order_item_discount', 'order_item_discount_rate', 'order_item_id', 'order_item_product_price', 'order_item_profit_ratio', 'order_item_quantity', 'sales', 'order_item_total', 'order_profit_per_order', 'order_region', 'order_state', 'order_status', 'product_card_id', 'product_category_id', 'product_name', 'product_price', 'product_status', 'shipping_date_dateorders', 'shipping_mode', 'shipping_delay', 'order_year', 'order_month', 'order_month_name', 'order_quarter', 'order_month_year', 'profit_margin', 'delivery_flag', 'discount_band']

In [69]:
from pathlib import Path
import pandas as pd

output_file = Path("./supply_chain.sql")

# Convert pandas dtype to PostgreSQL datatype
def get_postgres_type(dtype):
    if pd.api.types.is_integer_dtype(dtype):
        return "BIGINT"
    elif pd.api.types.is_float_dtype(dtype):
        return "DOUBLE PRECISION"
    elif pd.api.types.is_datetime64_any_dtype(dtype):
        return "TIMESTAMP"
    else:
        return "TEXT"


with open(output_file, "w", encoding="utf-8") as f:

    # Drop table if it already exists
    f.write("DROP TABLE IF EXISTS supply_chain;\n\n")

    # Create table
    f.write("CREATE TABLE supply_chain (\n")

    column_definitions = []

    for col in df.columns:
        pg_type = get_postgres_type(df[col].dtype)
        column_definitions.append(f'    "{col}" {pg_type}')

    f.write(",\n".join(column_definitions))
    f.write("\n);\n\n")

    # PostgreSQL COPY command
    columns = ", ".join(f'"{col}"' for col in df.columns)

    f.write(
        f"COPY supply_chain ({columns}) "
        "FROM STDIN WITH (FORMAT csv, HEADER true, NULL '\\N');\n"
    )

    # Write the actual data
    df.to_csv(
        f,
        index=False,
        header=True,
        na_rep="\\N"
    )

    # End COPY data
    f.write("\\.\n")


print("SQL file created successfully!")
print("Location:", output_file.resolve())
print("Size:", round(output_file.stat().st_size / (1024 * 1024), 2), "MB")

SQL file created successfully!
Location: C:\Users\thris\OneDrive\Desktop\Supplychain Anlysis\python\supply_chain.sql
Size: 82.67 MB

In [70]:
from pathlib import Path

def get_postgres_type(dtype):
    if pd.api.types.is_integer_dtype(dtype):
        return "BIGINT"
    elif pd.api.types.is_float_dtype(dtype):
        return "DOUBLE PRECISION"
    elif pd.api.types.is_datetime64_any_dtype(dtype):
        return "TIMESTAMP"
    else:
        return "TEXT"

sql_file = Path("./create_supply_chain.sql")

with open(sql_file, "w", encoding="utf-8") as f:

    f.write("DROP TABLE IF EXISTS supply_chain;\n\n")

    f.write("CREATE TABLE supply_chain (\n")

    columns = []

    for col in df.columns:
        pg_type = get_postgres_type(df[col].dtype)
        columns.append(f'    "{col}" {pg_type}')

    f.write(",\n".join(columns))
    f.write("\n);\n")

print(sql_file.resolve())

C:\Users\thris\OneDrive\Desktop\Supplychain Anlysis\python\create_supply_chain.sql

In [72]:
df.to_csv(
    "./supply_chain_cleaned.csv",
    index=False
)

In [73]:
print(df.shape)
print(len(df.columns))

(180519, 54)
54

In [74]:
df.to_csv(
    "./supply_chain_cleaned_utf8.csv",
    index=False,
    encoding="utf-8"
)

print(df.shape)
print("UTF-8 CSV created")

(180519, 54)
UTF-8 CSV created